### ISSUE TITLE
Demo z higrometrem EPIC

### ISSUE THREAD

**Issue by Jblew** [Jblew/iot2firebase#1]
- [x] Utworzyć multirepo z hierarchiczną konfiguracją
- [x] Utworzyć projekt firebase
- [x] Stworzyć pakiet iot - setup.sh - tworzy topic pubsub, inicjalizuje mqtt, robi ten topic domyslnym dla mqtt
- [x] iot — create-device.sh
- [x] Stworzyć funkcję chmurową, która będzie zapisywała do wybranego subfolderu firestore JSON nadeslany przez czujnik
- [x] Stworzyć template firmware
- [x] Kupić higrometr
- [x] (W) oczekiwanie na paczkę
- [x] Podłączyć do czujnika higrometr i skonfigurowac wysylanie

**Comment by Jblew** [comment]
Done
